#!/bin/bash

VIDDIR=$(dirname $1)
FPS=$(zenity --width 200 --height 100 --entry --title "avi to gif" --text="Please enter the frame rate.")

if [ -z "$FPS" ]
  then
      exit
fi

notify-send -i video-x-generic.png "gif2mp4" "Converting $(basename "$1") ..."

ffmpeg -i "$1" -r "$FPS" $VIDDIR/${1//.avi/.gif}

notify-send -i video-x-generic.png "$(basename "$1") converted"

