#!/bin/bash


#After sellecting you cant paste text with middle mouse button
echo ${NAUTILUS_SCRIPT_CURRENT_URI#file://}/$1 | xsel 

#coping with Ctrl+Shit+V
echo ${NAUTILUS_SCRIPT_CURRENT_URI#file://}/$1 | xsel -b
