#!/bin/bash


program="clipit"
msg="Program $program not found"
type $program > /dev/null || zenity --error --text="$msg" || notify-send "$msg"

#After sellecting you can paste text with ctrl+V
echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | $program
