#!/bin/bash

VIDDIR=$(dirname $1)
FPS=$(zenity --width 200 --height 100 --entry --title "avi to gif" --text="Please enter the frame rate.")

if [ -z "$FPS" ]
  then
      exit
fi

notify-send -i video-x-generic.png "gif2mp4" "Converting $(basename "$1") ..."

#ffmpeg -i "$1" -r "$FPS" $VIDDIR/${1//.avi/.gif}
ffmpeg -i "$1" -r "$FPS" "$VIDDIR"/converted.gif
if [[  "$?" -eq 0 ]]; then
  notify-send -i video-x-generic.png "$(basename "$1") converted"
else
  notify-send "echo $?"
fi
