#!/bin/bash

# This script converts .wav file to mp3, ogg, acc.
# Dependencies: ffmpeg, zenity

choice=$(zenity  --list  --text "Convert wav to:" --radiolist  --column "Pick" --column "Opinion" TRUE "ogg" FALSE "mp3" FALSE "ac3")
VIDDIR=$(dirname $1)

if [[  "$?" -eq 0 ]]; then

    for filename in "$@"
    do
        # Example: file_name.wav
        extension="${filename##*.}" # .waw - part
        fname="${filename%.*}"      # file_name - part
        
        if [[ $extension == "wav" ]]; then
                case "$choice" in
                    "mp3")
                        ffmpeg -i "$filename" -acodec libmp3lame "$fname".mp3

                        ;;
                        
                    "ogg")

                        ffmpeg -i "$filename" -acodec libvorbis "$fname".ogg

                        ;;
                        

                    "ac3")
                    
                        ffmpeg -i "$filename" -acodec ac3  "$fname".ac3
                        
                        ;;                    

                esac

        fi
    done
fi


