#!/bin/bash

## Webm convert 0.1
## Dependencies: libav-tools, notify-osd
# avconv 
## -y  Overwrite output files without asking.


avconv -y -i "$1" -acodec libvorbis -aq 5 -ac 2 -qmax 25 -threads 2 converted.webm
notify-send -i emblem-default "Video conversion" "completed"
