#!/bin/bash

# This script compresses png files

program="pngquant"
msg="Program $program not found"
type $program > /dev/null || zenity --error --text="$msg" || notify-send "$msg" && exit 1

for filename in "$@"
do
    extension="${filename##*.}"
    if [[ $extension == "png" ]]; then

            pngquant "$filename"

    fi
done
